### ISSUE TITLE
Support for non-integer IDs

### ISSUE THREAD

**Issue by aidandamerell** [aribouius/jsonapi-react#12]
Non integer IDs do not appear to get tracked as part of the cache and therefore use of `useMutation` treats these as `create` actions. This causes issues with UUID primary keys.

Is there some way to fix this in the schema or is this an underlying issue?

Thanks,

**Comment by aribouius** [comment]
@aidandamerell hey thanks for reporting this.  It looks like an underlying issue, but one that should be relatively easy to fix.  Give me a day or two to patch it up!

**Comment by aidandamerell** [comment]
@aribouius Awesome, thanks Ari! Great project btw!

**Comment by aribouius** [comment]
@aidandamerell a patch for this is now available on version `0.0.16`.

Relevant commit can be seen [here](https://github.com/aribouius/jsonapi-react/commit/bd3208cda7ccf16abff0498b241a5a104befee93).

**Comment by aidandamerell** [comment]
Excellent work, thanks @aribouius!
