### ISSUE TITLE
question: Typescript support

### ISSUE THREAD

**Issue by rchavik** [aribouius/jsonapi-react#13]
Is there plan to officially support typescript?

**Comment by aribouius** [comment]
Hi @rchavik, I'm not a typescript user myself, but certainly wouldn't be opposed to supporting it.  It's unfortunately not something I have bandwidth to tackle at the moment, but PR's are welcome :)

**Comment by rchavik** [comment]
I will try.

Thanks

**Comment by timothyjoh** [comment]
Any luck so far @rchavik ?

**Comment by rchavik** [comment]
Sorry, no.

**Comment by nlap** [comment]
I had a chance to add types in #20 - feedback welcome!

**Comment by aribouius** [comment]
Types have been added via https://github.com/aribouius/jsonapi-react/pull/20
