### ISSUE TITLE
How to set initialData?

### ISSUE THREAD

**Issue by Steffi3rd** [aribouius/jsonapi-react#32]
Hello guys 👋

I'm trying this lib using Next.js with SSR

I would like to set `initialData` as shown in this commit : https://github.com/aribouius/jsonapi-react/commit/b0e1960d1031497b7d876d71d668bec9c42ed93d, but I can't make it work, `data` of `useQuery` returns `undefined` at the first time : 

```
export default function Index({ resultFromGetServerSideProps = "test" }) {
   const { data, meta, error, isLoading, isFetching } = useQuery([
      'news', {
        include: ['city'],
        initialData: resultFromGetServerSideProps,
      },
   ])

   console.log(data)
}
```

**console.log :** 
First render : `undefined`
Re-render : `{ ... }`

Someone knows how to set `initialData` please?

**Comment by aribouius** [comment]
Hey @Steffi3rd looks like you are passing `initialData` in the wrong place.  

The signature of that hook is `useQuery(query, options)`, so you're attempting to pass in an option param via the query arg.

The correct implementation would be
```javascript
const { 
  data, 
  meta, 
  error, 
  isLoading, 
  isFetching 
} = useQuery(['news', { include: ['city'] }], {
  initialData: resultFromGetServerSideProps,
})
```

**Comment by Steffi3rd** [comment]
Oh yeah, my bad. Thank you very much @aribouius! It works now 😍

--- 
I just a Typescript error using `initialData` :

<img width="774" alt="Capture d’écran 2021-05-21 à 10 04 04" src="https://user-images.githubusercontent.com/814410/119105982-25bf2080-ba1e-11eb-9392-a8e1f9264e62.png">
<img width="732" alt="Capture d’écran 2021-05-21 à 10 04 10" src="https://user-images.githubusercontent.com/814410/119105987-26f04d80-ba1e-11eb-9c0d-5738064c38a3.png">

**Comment by Steffi3rd** [comment]
With @cta-faber, we've opened a PR to fix that : https://github.com/aribouius/jsonapi-react/pull/34
