### ISSUE TITLE
Is there a way to intercept requests and responses?

### ISSUE THREAD

**Issue by npearson72** [aribouius/jsonapi-react#38]
As the title says. Similar to how axios allows you interceptors.

**Comment by aribouius** [comment]
@npearson72 not at the moment, although it's something I'd love to build better support for.

While not advertised, the library does allow overriding the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) method that is used to execute requests.  This means you could provide a custom one that uses axios under the hood.

**Comment by npearson72** [comment]
Thanks @aribouius
