### ISSUE TITLE
use it with redux-saga 

### ISSUE THREAD

**Issue by alzizoomar** [aribouius/jsonapi-react#39]
How to use useQuery and the other hooks with redux-saga generator function to fetch my data?

**Comment by alzizoomar** [comment]
@aribouius if you can help, please

**Comment by aribouius** [comment]
@alzizoomar i don't use redux saga, so my knowledge of the best way to integrate it is limited.

My best guess is that you'll want to execute API requests using a [client](https://github.com/aribouius/jsonapi-react#ApiClient) instance.
```javascript
import { ApiClient } from 'jsonapi-react'

function* fetchUsers() {
  const client = new ApiClient(...)
}
```

The tricky part I'm not sure about, is that the client instance is not thread safe, meaning you'll need to either create a new instance of it inside each saga function, or find a way to pass a single instance of it (per request) to each generator function.
