### ISSUE TITLE
Atomic Operations

### ISSUE THREAD

**Issue by rachael-ross** [aribouius/jsonapi-react#41]
Just wondering if the specification extension for atomic operations is slated to be supported any time soon?

https://jsonapi.org/ext/atomic/

**Comment by aribouius** [comment]
Hi @rachael-ross yes I'm actively trying to figure out how to best support it.  The main friction point right now is that this library currently tries to abstract away as much of the JSON:API schema details, to allow working with objects that only contain the resource attributes (i.e. [this](https://github.com/aribouius/jsonapi-react#normalization)).

Odds are it will be included as part of the next major version release, and will be accompanied by some breaking changes to how this library works with resource objects.
