### ISSUE TITLE
Getting cannot read properties of undefined (reading 'ssrMode') 

### ISSUE THREAD

**Issue by bhavesh1334** [aribouius/jsonapi-react#53]
![ss135](https://user-images.githubusercontent.com/50066490/157931634-a953e843-25ce-491c-8769-2d4180a4e05a.png)

**Comment by bhavesh1334** [comment]
> ![ss135](https://user-images.githubusercontent.com/50066490/157931634-a953e843-25ce-491c-8769-2d4180a4e05a.png)

Getting this error from couple of days , tried enough but doesn't get any possible solution.

**Comment by aribouius** [comment]
Hi @bhavesh1334,

It looks like the library could employ some better exception handling here, but the issue on your side appears to be that you are attempting to use `useQuery` outside the `ApiProvider` context.

Restructuring your code in the following manner should do the trick:
```javascript
function App(props) {
  const query = useQuery('posts')
  
  return (
    <div>
      <h1>Hello</h1>
    </div>
  )
}

const root = (
  <ApiProvider client={client}>
    <App />
  </ApiProvider>
)

React.render(root, document.getElementById('root'))
```
