### ISSUE TITLE
Update using POST instead of PATCH

### ISSUE THREAD

**Issue by hoIIer** [aribouius/jsonapi-react#58]
I have an item previously returned by the api in the form:
```
  {
    id: 1,
    fieldA: 'abc',
  }
```
where the schema is defined as:
```
    schema: {
      widgets: {
        type: 'widgets',
        fields: {
          fieldA: {
            type: 'string',
            readOnly: true,
          },
          fieldB: 'string',
        }
      }
    }
```
I want to do a PATCH request which according to the docs `Defaults to POST when creating a resource, and PATCH when updating`.

I am doing the following which is resulting in a `POST` instead of a `PATCH`.
```
  const [patchWidget] = useMutation('widgets');

  const submit = async (widget) => {
    widget.fieldB = new Date();

    await patchWidget(widget));
  }
```

What is the proper way to create a `PATCH` request without specifying it as an option in the mutation?

e.g. `PATCH /api/widgets/1`

### edit

I was able to get it working with
```
    const res = await client.mutate(['widgets', widget.id], {
      fieldB: new Date(),
    });
```
But will leave open because wondering if I need to use the client directly to get PATCH behavior

**Comment by aribouius** [comment]
@holler the `useMutation` hook works the same as the client.  This should work:

```
const [patchWidget] = useMutation(['widgets', widget.id]);
```

**Comment by hoIIer** [comment]
@aribouius ah I see, thanks!
